name = "blaze-intelligence"
compatibility_date = "2025-08-20"

# Pages output directory (serving from root)
pages_build_output_dir = "./"

# Page-level environment variables (non-secrets)
[vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://blaze-intelligence.com"
API_VERSION = "v1"
CACHE_TTL = "3600"

# Production environment
[env.production.vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://blaze-intelligence.com"
CACHE_TTL = "3600"

# Preview environment (for branch deployments)
[env.preview.vars]
ENVIRONMENT = "preview"
API_BASE_URL = "https://blaze-intelligence.pages.dev"
API_VERSION = "v1"
CACHE_TTL = "60"

# KV Namespace bindings (uncomment and add IDs after creation)
# [[kv_namespaces]]
# binding = "ANALYTICS_KV"
# id = "your_analytics_kv_id"

# [[kv_namespaces]]
# binding = "LEADS_KV" 
# id = "your_leads_kv_id"

# [[kv_namespaces]]
# binding = "CONTENT_KV"
# id = "your_content_kv_id"