name = "blaze-intelligence"
compatibility_date = "2025-08-20"

# Pages output directory (serving from root)
pages_build_output_dir = "./"

# Page-level environment variables (non-secrets)
[vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://blaze-intelligence.com"
API_VERSION = "v1"
CACHE_TTL = "3600"

# Production environment
[env.production.vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://blaze-intelligence.com"
CACHE_TTL = "3600"

# Preview environment (for branch deployments)
[env.preview.vars]
ENVIRONMENT = "preview"
API_BASE_URL = "https://blaze-intelligence.pages.dev"
CACHE_TTL = "60"