import { SluggerProfile } from './gameTypes';

export const sluggerProfiles: SluggerProfile[] = [
  {
    id: 'maya-solar-flare',
    name: 'Maya Ortiz',
    nickname: 'Solar Flare',
    hometown: 'Santa Fe, NM',
    description:
      'A sandlot strategist who studies meteorology to predict wind gusts before every at-bat.',
    battingStyle: 'switch',
    timingWindow: 165,
    power: 4,
    contact: 5,
    confidence: 4,
    primaryColor: '#ff8f5b',
    accentColor: '#ffe08a',
    featuredEmoji: '☀️',
    signatureMove: 'Solar Shift stride that keeps timing windows wide even on curveballs.',
  },
  {
    id: 'leo-high-noon',
    name: 'Leo Carver',
    nickname: 'High-Noon',
    hometown: 'Abilene, TX',
    description:
      'Quick-draw bat speed and cowboy swagger. Leo narrates every swing like a radio broadcaster.',
    battingStyle: 'right',
    timingWindow: 150,
    power: 5,
    contact: 3,
    confidence: 5,
    primaryColor: '#ffbe3d',
    accentColor: '#753500',
    featuredEmoji: '🤠',
    signatureMove: 'Sunrise Launch that turns perfect swings into towering two-run blasts.',
  },
  {
    id: 'ayumi-starburst',
    name: 'Ayumi Takahashi',
    nickname: 'Starburst',
    hometown: 'Pearl City, HI',
    description:
      'A multi-sport dynamo who choreographs pre-pitch dances that distract every pitcher in the league.',
    battingStyle: 'left',
    timingWindow: 175,
    power: 3,
    contact: 5,
    confidence: 3,
    primaryColor: '#6be4ff',
    accentColor: '#ff82e6',
    featuredEmoji: '🌺',
    signatureMove: 'Polynesian Pop swing with late acceleration for line-drive consistency.',
  },
  {
    id: 'ezra-comet',
    name: 'Ezra Miles',
    nickname: 'Comet Tail',
    hometown: 'Flagstaff, AZ',
    description:
      'Astrophysics prodigy who tracks spin axis charts in a pocket notebook mid-game.',
    battingStyle: 'right',
    timingWindow: 155,
    power: 4,
    contact: 4,
    confidence: 3,
    primaryColor: '#5c73ff',
    accentColor: '#a2b6ff',
    featuredEmoji: '☄️',
    signatureMove: 'Zero-Gravity load that keeps the barrel level through the zone.',
  },
  {
    id: 'nina-sonic-bloom',
    name: 'Nina Park',
    nickname: 'Sonic Bloom',
    hometown: 'Portland, OR',
    description:
      'Produces indie pop tracks inspired by crack-of-the-bat rhythms and loves wet-weather games.',
    battingStyle: 'left',
    timingWindow: 185,
    power: 3,
    contact: 4,
    confidence: 5,
    primaryColor: '#00d5a6',
    accentColor: '#7efdda',
    featuredEmoji: '🎶',
    signatureMove: 'Amplified follow-through that turns rallies into sing-along celebrations.',
  },
  {
    id: 'omar-rocket',
    name: 'Omar Castell',
    nickname: 'Rocket Script',
    hometown: 'Baton Rouge, LA',
    description:
      'Codes his own swing analytics during rain delays and loves smashing data-driven dingers.',
    battingStyle: 'switch',
    timingWindow: 160,
    power: 4,
    contact: 4,
    confidence: 4,
    primaryColor: '#ff6bc0',
    accentColor: '#4c1a3e',
    featuredEmoji: '🚀',
    signatureMove: 'Algorithmic stride that adapts timing windows in real time.',
  },
];
