import { StadiumProfile } from './gameTypes';

export const stadiumProfiles: StadiumProfile[] = [
  {
    id: 'sunset-sandlot',
    name: 'Sunset Sandlot',
    location: 'El Paso, TX',
    backdrop: 'Desert mesas bathed in gold hour light',
    vibe: 'Warm breezes and upbeat mariachi riffs between innings',
    weatherBias: 'Dry air keeps the ball flying',
    timingBonus: 15,
    powerBonus: 0.25,
    cpuRunDistribution: [0.48, 0.32, 0.16, 0.04],
    skyColor: '#f7b267',
    turfColor: '#2d8b57',
    infieldColor: '#a97142',
    accentColor: '#ffdd99',
    capacity: 'Backyard blankets + fold-out chairs (280 fans)',
  },
  {
    id: 'riverbend-rail-yard',
    name: 'Riverbend Rail Yard',
    location: 'Davenport, IA',
    backdrop: 'Freight cranes and moonlit river reflections',
    vibe: 'Train whistles double as rally horns',
    weatherBias: 'Humid air keeps breaking pitches nasty',
    timingBonus: 5,
    powerBonus: 0.1,
    cpuRunDistribution: [0.42, 0.34, 0.18, 0.06],
    skyColor: '#4b6dff',
    turfColor: '#2f6f5f',
    infieldColor: '#6a4d32',
    accentColor: '#a0c9ff',
    capacity: 'Converted boxcars (420 fans)',
  },
  {
    id: 'meteor-shower-dome',
    name: 'Meteor Shower Dome',
    location: 'Truth or Consequences, NM',
    backdrop: 'LED constellations flicker across a translucent dome',
    vibe: 'Synthwave scoreboard animations pulse with each swing',
    weatherBias: 'Climate-controlled air rewards pure bat speed',
    timingBonus: 25,
    powerBonus: 0.15,
    cpuRunDistribution: [0.5, 0.28, 0.16, 0.06],
    skyColor: '#141c4f',
    turfColor: '#1f8a70',
    infieldColor: '#44315a',
    accentColor: '#ff6fb7',
    capacity: 'Geodesic bleachers (510 fans)',
  },
  {
    id: 'harborlight-pier',
    name: 'Harborlight Pier',
    location: 'Astoria, OR',
    backdrop: 'Floating lanterns and fishing boats cheering from the bay',
    vibe: 'Sea shanties remixed with lo-fi beats',
    weatherBias: 'Marine layer knocks down lazy fly balls',
    timingBonus: 30,
    powerBonus: 0.05,
    cpuRunDistribution: [0.56, 0.28, 0.12, 0.04],
    skyColor: '#6ab7ff',
    turfColor: '#3e7a59',
    infieldColor: '#71513a',
    accentColor: '#d6f3ff',
    capacity: 'Boardwalk benches (360 fans)',
  },
];
